language: clojure
jdk:
- openjdk8
- openjdk11
deploy:
  skip_cleanup: true
  provider: script
  script: lein deploy
  on:
    tags: true
    jdk: openjdk8
env:
  global:
  - secure: NGWel52i2009kLxjzL70Q2000634giky2+62ibppe9kCFvFpWmL3s4/ax20jLGvjC2PWHu8tNMGeAkL5IL3hHKk0ynC+Z1eGHhYXQS4mQeIi3yUtRQMaD0WJzpQbU0N7xRIthH0eQa+KSO8XBzSPO1PH7U9y3xV6/++7sMXIAe0=
  - secure: RsOrpiyAGPdwXFVO/rbS2BnSlmDQWTsyAeCfxwVA9rLGcTcmrfIX0ClCwfYbO+mVU5kTN/BKPglMVXzKka3hp+aYwnyD1D/GbwBvx/U4Dpu7AXw1ES6LsG9XmyNvcUoxCwt9ZsKtrQL2+o952Bjtt8q3eyEJafMy0r5q7mt26sE=
